### ISSUE TITLE
Possible NullPointerException on add_file

### ISSUE THREAD

**Issue by pilz** [JavaDogs/cws#57]
By accident we might have discovered a NullPointerException.

See https://gist.githubusercontent.com/ale-rt/2d6ed2bd8295656358bb7e2cbc46d447/raw/366da59e6cc6b15832275194ec64b256d71b3af2/gistfile1.txt

It might happen when adding a file and then again trying to add the same file with the same id.

**Comment by knjensen** [comment]
A new test was added, that verified that with a broken DB, there did indeed come an NPE. Added a check that will respond with an error and a text message for the administrators to correct the database manually. Fixing a missing root folder is fairly simply, a new metadata record is added, and all existing objects must have this as their parent.

**Comment by pilz** [comment]
Great job!
